// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PFE_API;

#nullable disable

namespace PFE_API.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20240421103620_addEmployee")]
    partial class addEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PFE_API.Model.ContratRT", b =>
                {
                    b.Property<string>("CodeContrat")
                        .HasColumnType("text");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("CategorieContrat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFinPeriodeEssai")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MatriculeEmp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegimeTravail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CodeContrat");

                    b.ToTable("ContratsRT");
                });

            modelBuilder.Entity("PFE_API.Model.Employee", b =>
                {
                    b.Property<string>("Matricule")
                        .HasColumnType("text");

                    b.Property<string>("CommuneNaissance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IDEquipe")
                        .HasColumnType("integer");

                    b.Property<string>("IDResponsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsResponsable")
                        .HasColumnType("boolean");

                    b.Property<string>("LieuNaissance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NSS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationalites")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomArabe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomJeuneFille")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaysNaissance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom2Arabe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrenomArabe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Reliquat")
                        .HasColumnType("integer");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SituationFamiliale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WilayaNaissance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Matricule");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
