// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PFE_API;

#nullable disable

namespace PFE_API.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20240603134137_employee-bulable-fields")]
    partial class employeebulablefields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PFE_API.Model.Conge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("date");

                    b.Property<int>("IDExercice")
                        .HasColumnType("integer");

                    b.Property<string>("MatriculeEmp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Conges");
                });

            modelBuilder.Entity("PFE_API.Model.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("MatriculeEmp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("PFE_API.Model.ContratRT", b =>
                {
                    b.Property<string>("CodeContrat")
                        .HasColumnType("text");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("CategorieContrat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFinPeriodeEssai")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MatriculeEmp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegimeTravail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CodeContrat");

                    b.ToTable("ContratsRT");
                });

            modelBuilder.Entity("PFE_API.Model.Demande", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date");

                    b.Property<int>("EtatActuel")
                        .HasColumnType("integer");

                    b.Property<int>("Importance")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsRemuneree")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("JourRecup")
                        .HasColumnType("date");

                    b.Property<string>("LienVersJustification")
                        .HasColumnType("text");

                    b.Property<string>("MatriculeEmp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NouvelleInformationMatricule")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("TypeConge")
                        .HasColumnType("integer");

                    b.Property<int?>("TypeDoc")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("NouvelleInformationMatricule");

                    b.ToTable("Demandes");
                });

            modelBuilder.Entity("PFE_API.Model.Employee", b =>
                {
                    b.Property<string>("Matricule")
                        .HasColumnType("text");

                    b.Property<string>("CommuneNaissance")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateEntre")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateSortie")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int?>("IDEquipe")
                        .HasColumnType("integer");

                    b.Property<string>("IDResponsable")
                        .HasColumnType("text");

                    b.Property<bool>("IsResponsable")
                        .HasColumnType("boolean");

                    b.Property<string>("LieuNaissance")
                        .HasColumnType("text");

                    b.Property<string>("LinkToPhoto")
                        .HasColumnType("text");

                    b.Property<string>("NSS")
                        .HasColumnType("text");

                    b.Property<string>("Nationalites")
                        .HasColumnType("text");

                    b.Property<int?>("NbAnneeExperienceExterne")
                        .HasColumnType("integer");

                    b.Property<int?>("NbAnneeExperienceInterne")
                        .HasColumnType("integer");

                    b.Property<int?>("NbEnfant")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.Property<string>("NomArabe")
                        .HasColumnType("text");

                    b.Property<string>("NomJeuneFille")
                        .HasColumnType("text");

                    b.Property<string>("NomJeuneFilleArabe")
                        .HasColumnType("text");

                    b.Property<string>("PaysNaissance")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .HasColumnType("text");

                    b.Property<string>("Prenom2")
                        .HasColumnType("text");

                    b.Property<string>("Prenom2Arabe")
                        .HasColumnType("text");

                    b.Property<string>("PrenomArabe")
                        .HasColumnType("text");

                    b.Property<int?>("Reliquat")
                        .HasColumnType("integer");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("Sexe")
                        .HasColumnType("integer");

                    b.Property<int>("SituationFamiliale")
                        .HasColumnType("integer");

                    b.Property<int>("Titre")
                        .HasColumnType("integer");

                    b.Property<string>("WilayaNaissance")
                        .HasColumnType("text");

                    b.HasKey("Matricule");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PFE_API.Model.Equipe", b =>
                {
                    b.Property<int>("IDEquipe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDEquipe"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomEquipe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IDEquipe");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("PFE_API.Model.Exercice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Annee")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.ToTable("Exercices");
                });

            modelBuilder.Entity("PFE_API.Model.Historique", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromEtat")
                        .HasColumnType("integer");

                    b.Property<int>("IDDemande")
                        .HasColumnType("integer");

                    b.Property<string>("Par")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ToEtat")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Historiques");
                });

            modelBuilder.Entity("PFE_API.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PFE_API.Model.Demande", b =>
                {
                    b.HasOne("PFE_API.Model.Employee", "NouvelleInformation")
                        .WithMany()
                        .HasForeignKey("NouvelleInformationMatricule");

                    b.Navigation("NouvelleInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
